// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKZyvhymUI4UKui-UwKPtixrmYJpmi4PA',
    appId: '1:972330708504:web:ea49ea1b925560a0d8dd6d',
    messagingSenderId: '972330708504',
    projectId: 'colleagues-4d12b',
    authDomain: 'colleagues-4d12b.firebaseapp.com',
    storageBucket: 'colleagues-4d12b.appspot.com',
    measurementId: 'G-9NP62497V8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCojvU6JVc0dRdfxiQ6gBlZRPnt42r7B6w',
    appId: '1:972330708504:android:513d836589f6dbced8dd6d',
    messagingSenderId: '972330708504',
    projectId: 'colleagues-4d12b',
    storageBucket: 'colleagues-4d12b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5Y2XdF4ASGbI25_ZH5x1-bM9kVZJ9ijw',
    appId: '1:972330708504:ios:9551c9b74f4a457bd8dd6d',
    messagingSenderId: '972330708504',
    projectId: 'colleagues-4d12b',
    storageBucket: 'colleagues-4d12b.appspot.com',
    iosBundleId: 'com.example.collegeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5Y2XdF4ASGbI25_ZH5x1-bM9kVZJ9ijw',
    appId: '1:972330708504:ios:85089557b889a2d5d8dd6d',
    messagingSenderId: '972330708504',
    projectId: 'colleagues-4d12b',
    storageBucket: 'colleagues-4d12b.appspot.com',
    iosBundleId: 'com.example.collegeApp.RunnerTests',
  );
}
